### ISSUE TITLE
Web Certificate Management

### ISSUE THREAD

**Issue by mlorenz1-lenovo** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#163]
We are integrating our Solution with the toolkit and now we need to use our own custom certificates to secure all the communication. A self-signed certificate is being generated, by the API Gateway since we didn't add one, for all HTTPS/WSS communication in MPS/RPS, but we are having issues to provide our certificates to the toolkit. My question is: Is there a proper way to configure it in the Azure, API Gateway or even in the application (MPS) ?

**Comment by rsdmike** [comment]
For configuring Kong, you can mount a `./certs` volume into the container with your private key and certificate and then add two ENV variables that point to those files that are mounted in. For example:

``` yaml
kong:
    image: kong:2.3
    environment:
      - KONG_SSL_CERT=/ssl/cert.crt
      - KONG_SSL_CERT_KEY=/ssl/key.pem
    volumes:
      - ./kong.yaml:/home/kong/kong.yml
      - ./certs:/ssl
```
