### ISSUE TITLE
nsCertType should not be used for CIRA TLS verification.

### ISSUE THREAD

**Issue by jclab-joseph** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#165]
**Describe the bug** 🪲

As of OpenSSL v1.1, the nsCertType extension in X.509 certificates are no longer supported. This extension is old and has been deprecated for a long time. 

However, AMT Device still requires nsCertType. Certificates generated outside of MPS may not have nsCertType . In this case, the TLS Handshake fails.

**Expected behavior**

Of the X509 extensions, nsCertType should not be mandatory.

**Screenshots** 🖼️

Unfortunately, I turned off Wireshark.

After Server Hello, Client (AMT) returns "Certificate Unknown (code 46)".

**AMT Device (please complete the following information):** 🖥️
 - AMT Version: 12.0.92 build number 2145
 - AMT Configuration Mode: Admin Control Mode
 - Network Configuration: Dynamic IP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: K8s with cert-manager

**Comment by graikhel-intel** [comment]
@jclab-joseph I removed the extension **nsCertType** when generating CIRA self-signed cert from MPS code. Tested it on AMT device (Version 12.0.92 and build no 2145) and everything works as expected (did not see any connection issues). 

Please take a look at the code change here https://github.com/open-amt-cloud-toolkit/mps/commit/b60d9e8219ea00a1078e6ec7fa0d95dfd11e2ebe. Snapshot of Root certificate (on left) and Server certificate (on right)

![image](https://user-images.githubusercontent.com/52047020/213329591-050e45a9-e021-4b53-b3b2-4e92664c9662.png)


I noticed **Certificate Unknown (code 46)** message in Wireshark when server certificate (SSL cert) is missing the extension **Enhanced Key Usage**. Could you please try adding the 'Enhanced Key Usage' extension to server cert and see if that works?


Also, I did not try generating self-signed cert using openssl yet, going to give that a try as well.

**Comment by jclab-joseph** [comment]
Same "X509v3 Extended Key Usage" exists.

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            1c:02:c3:28:bb:2b:d4:be:db:aa:b8:98:00:12:e2:0c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = CompanyName, CN = MPS Mesh Root
        Validity
            Not Before: Jan 10 01:25:35 2023 GMT
            Not After : Jan  9 01:25:35 2026 GMT
        Subject: O = CompanyName, CN = amt.domain.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (3072 bit)
                Modulus:
                    00:b4:71:9c:65:a8:90:a2:33:dc:18:61:6f:e7:1a:
                    b4:80:89:b4:1a:41:c2:04:af:e1:e8:b4:f7:10:d4:
                    11:66:e2:9b:c6:d1:7a:5e:d7:c0:84:39:cd:20:6e:
                    ac:cb:34:ff:c1:bd:0d:ab:83:23:84:f9:5c:34:47:
                    a4:52:9e:84:87:de:7f:1d:b7:ac:69:04:2f:87:d4:
                    ef:37:fb:de:6f:ad:5c:96:e5:93:23:d2:58:ce:4d:
                    6b:1c:37:39:e2:67:4f:0d:bb:d7:31:57:23:d0:9f:
                    e4:6d:1c:7f:c2:e9:ea:a9:05:0a:87:87:ec:af:25:
                    80:52:c7:bc:a4:a7:2d:57:84:a1:36:f2:6d:0a:c1:
                    7c:1f:af:67:c3:ac:d8:25:9e:b1:28:65:a8:1e:dd:
                    22:6b:f6:90:06:e1:ac:b8:e9:64:76:1d:32:58:36:
                    f6:0d:02:1a:9b:79:e4:38:a0:0a:43:f3:62:cf:0e:
                    1d:86:aa:49:16:6a:db:f9:52:ef:12:17:d5:34:4c:
                    3a:5b:08:f4:77:68:c6:65:53:ed:d7:85:95:62:03:
                    82:f0:fb:d3:28:e8:28:3d:79:17:15:74:2b:83:bd:
                    cc:98:4b:b5:ed:c3:b3:76:94:49:44:a9:d4:e3:eb:
                    61:3a:99:a8:64:b1:e5:7b:44:68:39:81:eb:8a:b4:
                    87:8e:17:de:0b:1e:7c:cc:c4:42:af:13:3b:0e:80:
                    a0:80:cf:8e:aa:36:3d:a1:9d:fa:cb:26:d6:9b:0d:
                    cb:06:a7:82:bd:d7:9b:65:e0:7f:47:1e:a8:cb:80:
                    4e:b5:43:ed:82:cd:5b:cb:32:71:3a:68:da:7c:c9:
                    04:54:7a:07:f0:fc:d9:d2:01:31:54:4a:10:12:c9:
                    da:93:98:d1:a1:6b:bf:bf:10:41:de:db:b8:d7:e1:
                    df:a7:ed:96:b8:e0:ad:70:61:88:b4:5e:07:4e:4a:
                    95:23:99:e8:a0:c6:59:53:62:6a:9e:44:da:23:f7:
                    06:3a:3e:96:6d:7a:92:de:2a:85
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Key Agreement
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier: 
                10:F6:E5:48:1E:37:C5:A0:6B:E0:13:0D:9A:0C:44:98:12:7C:0B:09
            X509v3 Subject Alternative Name: 
                DNS:amt.domain.com
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        0c:cd:10:68:83:50:c8:d8:19:3e:07:4e:0d:d3:32:fb:1d:2b:
        a0:61:28:23:36:d8:ca:fd:1e:e4:bd:1c:0a:bf:42:90:6f:ad:
        a7:0b:23:6e:66:15:45:51:fb:b7:66:f5:58:fb:fe:c8:2c:35:
        a3:dc:e3:ac:12:43:eb:98:e2:52:60:25:26:5e:4e:38:a9:43:
        5b:c5:35:a7:1a:e2:53:e5:7b:fb:04:9c:76:5a:8a:8e:46:81:
        f0:9d:fd:ef:15:db:57:8b:26:f6:16:9a:44:b6:09:cd:d9:dd:
        28:8c:17:e0:f8:c0:69:8d:74:4a:c0:b7:02:57:81:44:0b:ff:
        13:bf:f6:c1:96:6e:ee:88:6f:c1:29:0d:2a:d2:12:a1:36:b6:
        d6:32:af:27:2e:79:b9:27:33:82:16:e7:b8:b7:de:6b:f5:a8:
        1a:a7:f2:66:2b:b1:d8:c0:88:7b:e1:27:64:a4:59:25:de:42:
        6d:3f:5d:d1:c3:c3:22:08:2f:a3:a9:d6:55:c8:19:7c:94:ce:
        b2:c9:69:7e:02:7f:94:9e:96:4d:7a:50:18:56:dc:d2:64:47:
        85:b9:09:59:ac:b5:35:f6:17:45:a4:0d:d0:77:58:02:d6:7c:
        29:a1:ea:c7:93:18:d0:06:1b:0b:33:19:cd:43:61:7b:a8:1a:
        0b:72:2f:87:f7:32:3c:11:25:1c:2e:87:91:17:f9:a0:d2:76:
        7b:a2:44:c3:ef:ec:0b:12:f9:37:0d:91:cd:d8:04:86:f2:55:
        a0:7c:ed:d1:8f:9f:83:0e:d5:86:87:ff:36:4f:95:e9:31:eb:
        15:b0:b5:95:39:77:2d:25:94:4e:68:4a:f8:48:2d:15:7f:8c:
        04:70:66:c6:64:90:82:08:7f:55:4d:de:da:f1:ef:7a:f7:c6:
        f6:c1:d5:d8:2b:1d:af:0d:a2:05:a1:69:d2:7c:07:61:60:d5:
        fa:d0:e3:cd:40:33:e8:cb:50:8f:37:88:8c:55:0c:f3:b4:f8:
        98:73:d0:ea:3b:6e:0b:8c:29:0b:20:2c:a7:93:f4:03:b5:e3:
        8b:53:c6:80:46:f9:e4:3d:3e:d7:fc:66:bc:91:b0:50:66:b2:
        eb:a7:aa:60:9b:63:87:d6:c6:2e:8e:6d:6f:d2:96:bb:04:92:
        be:9b:e7:1a:15:f7:f1:ce:d8:f7:3a:7a:9f:44:02:66:08:2c:
        2b:28:29:4d:0a:8c:2e:4b:15:1e:aa:7a:0e:92:55:d3:f6:48:
        91:37:f1:c9:86:4d:c0:3d:52:d4:d8:03:d8:8f:14:84:c9:08:
        46:f4:17:f3:73:30:a8:da:2b:5b:03:d7:ca:33:5d:f6:cd:fe:
        99:b6:b5:cf:12:a4:53:da
```

The non-working certificate was created via cert-manager.

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "amt-mps-root"
spec:
  isCA: true
  duration: 87600h # 10 years
  commonName: "MPS Root"
  secretName: "amt-mps-root"
  subject:
    organizations:
      - "CompanyName"
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: "selfsigned"
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "amt-mps-root-issuer"
spec:
  ca:
    secretName: "amt-mps-root"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "amt-mps-tls"
spec:
  isCA: false
  duration: 26280h # 3 years
  commonName: "mps.domain.com"
  secretName: "amt-mps-tls"
  privateKey:
    algorithm: RSA
    size: 3072
  subject:
    organizations:
      - "ComanyName"
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - key agreement
    - server auth
  dnsNames:
    - mps.domain.com
  issuerRef:
    name: "amt-mps-root-issuer"
    kind: Issuer
    group: cert-manager.io
```
